"""descentcurve2pnw: washout regression registry (the driver's "database of trouble spots").

The checked-in fixture (washouts_2026_07_11.json, generated by tools/washouts.py from the
2026-07-11 Lightning drive logs) records every high-speed steering-override cluster: GPS, entry
speed, the recorded binding cap, and the curve direction (log convention: strAng < 0 = left on
this truck's raw Ford StePinComp signal).

VALIDATION-ONLY: this data never feeds control. The test asserts that for every washout where a
binding cap was recorded (cap below the actual entry speed — the washout signature), the NEW
penalty pipeline (hump penalty + descent guard at an assumed 4% grade + left factor when the
cluster was a left curve) demands an entry speed at least 3 mph BELOW the speed the truck actually
carried into the curve — i.e. the generic fix would have been slowing the truck at every recorded
trouble spot.
"""
import json
import os

from openpilot.selfdrive.controls.lib import pnw_vehicle as pv
from openpilot.selfdrive.controls.lib.pnw_vehicle import PnwVehicle

MPH = 0.44704
FIXTURE = os.path.join(os.path.dirname(__file__), "washouts_2026_07_11.json")
ASSUMED_GRADE_PITCH = -0.04   # rad; the I-90 washouts were on descents — assume a modest 4% grade


class FakeCP:
  def __init__(self, fp="", brand="", op_long=False):
    self.carFingerprint = fp
    self.brand = brand
    self.openpilotLongitudinalControl = op_long


def _veh(tmp_path, monkeypatch):
  monkeypatch.setattr(pv, "CURVE_CONFIG_PATH", str(tmp_path / "nope.json"))   # shipped defaults
  return PnwVehicle(FakeCP("FORD_F_150_LIGHTNING_MK1", "ford", op_long=True))


def test_fixture_present_and_covers_the_drive():
  with open(FIXTURE) as f:
    data = json.load(f)
  washouts = data["washouts"]
  assert len(washouts) > 100                     # the drive report counted 91 high-speed clusters
  binding = [w for w in washouts if w["binding"]]
  assert len(binding) >= 20                      # the op-long evening washouts all carry a VTSC cap
  # the driver-cited 18:12 washout (77 mph vs cap 71, downhill LEFT) must be in the registry
  assert any(abs(w["v_entry_ms"] - 34.5) < 0.5 and w["dir"] == "left" and w["binding"]
             for w in binding)


def test_new_pipeline_caps_at_least_3mph_below_every_recorded_entry(tmp_path, monkeypatch):
  veh = _veh(tmp_path, monkeypatch)
  with open(FIXTURE) as f:
    washouts = json.load(f)["washouts"]
  checked = 0
  for w in washouts:
    if not w["binding"]:
      continue                                   # no binding cap recorded -> nothing to regress against
    pen = veh.curve_speed_penalty_ms(w["cap_ms"], pitch_rad=ASSUMED_GRADE_PITCH,
                                     is_left=(w["dir"] == "left"))
    new_cap = w["cap_ms"] - pen
    assert new_cap <= w["v_entry_ms"] - 3.0 * MPH, \
      f"{w['id']}: new cap {new_cap / MPH:.1f} mph not 3 mph below entry {w['v_entry_ms'] / MPH:.1f} mph"
    checked += 1
  assert checked >= 20


def test_registry_never_used_for_control():
  """Guard: no control module may import/read the washout fixture (validation-only, driver rule)."""
  import glob
  root = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
  offenders = []
  for path in glob.glob(os.path.join(root, "**", "*.py"), recursive=True):
    if os.sep + "tests" + os.sep in path or path.endswith("washouts.py"):
      continue
    with open(path, encoding="utf-8", errors="ignore") as f:
      if "washouts_2026_07_11" in f.read():
        offenders.append(path)
  assert not offenders, f"washout fixture referenced by control code: {offenders}"
