"""descentcurve2pnw: washout regression registry (the driver's "database of trouble spots").

The checked-in fixture (washouts_2026_07_11.json, generated by tools/washouts.py from the
2026-07-11 Lightning drive logs) records every high-speed steering-override cluster: GPS, entry
speed, the recorded binding cap, and the curve direction (strAng > 0 = left: carState.steeringAngleDeg is
left-positive. Until 2026-09-24 the tool had it inverted, strAng < 0 = left, and every `dir` in this fixture
was backwards -- the fixture was regenerated with the fixed tool).

VALIDATION-ONLY: this data never feeds control. The test asserts that for every washout where a
binding cap was recorded (cap below the actual entry speed — the washout signature), the NEW
penalty pipeline (hump penalty + descent guard at an assumed 4% grade + left factor when the
cluster was a left curve -- neutral 1.0 by default since 2026-09-24) demands an entry speed at least 3 mph BELOW the speed the truck actually
carried into the curve — i.e. the generic fix would have been slowing the truck at every recorded
trouble spot.
"""
import json
import os

from openpilot.selfdrive.controls.lib import pnw_vehicle as pv
from openpilot.selfdrive.controls.lib.pnw_vehicle import PnwVehicle

MPH = 0.44704
FIXTURE = os.path.join(os.path.dirname(__file__), "washouts_2026_07_11.json")
ASSUMED_GRADE_PITCH = -0.04   # rad; the I-90 washouts were on descents — assume a modest 4% grade


class FakeCP:
  def __init__(self, fp="", brand="", op_long=False):
    self.carFingerprint = fp
    self.brand = brand
    self.openpilotLongitudinalControl = op_long


def _veh(tmp_path, monkeypatch):
  monkeypatch.setattr(pv, "CURVE_CONFIG_PATH", str(tmp_path / "nope.json"))   # shipped defaults
  return PnwVehicle(FakeCP("FORD_F_150_LIGHTNING_MK1", "ford", op_long=True))


def test_fixture_present_and_covers_the_drive():
  with open(FIXTURE) as f:
    data = json.load(f)
  washouts = data["washouts"]
  assert len(washouts) > 100                     # the drive report counted 91 high-speed clusters
  # the fixture must come from the FIXED tool (2026-09-24): the old strAng<0 = left labels were all inverted
  assert data["dir_convention"].startswith("strAng>0 = left"), data["dir_convention"]
  binding = [w for w in washouts if w["binding"]]
  assert len(binding) >= 20                      # the op-long evening washouts all carry a VTSC cap
  # the driver-cited 18:12 PT washout (77 mph vs cap 71) must be in the registry. It was long cited as a
  # "downhill LEFT" -- under the corrected convention it is a RIGHT-hander (#156, mean strAng -10.1 deg).
  assert any(abs(w["v_entry_ms"] - 34.5) < 0.5 and w["dir"] == "right" and w["binding"]
             for w in binding)
  # icbmslow2pnw (2026-09-17): the fixture as first checked in ENDED at 18:17 PT, because
  # ces_events_1917.jsonl was pulled off the device after it was generated. That silently left out
  # the 19:16-19:18 PT downhill-LEFT washouts -- the two events descentcurve2pnw's left_factor and
  # descent_gain were BUILT from (CURVESLOW2PNW.md "two DOWNHILL LEFT washouts ... 19:17-18"), so
  # the regression below had never actually been run against them. Regenerated with tools/washouts.py
  # over the full folder: 158 -> 171 clusters, 27 -> 35 binding. Nothing else changed.
  assert max(w["t"] for w in washouts) > 1783822200, \
    "the fixture stops before the 19:10+ PT washouts -- regenerate it with tools/washouts.py"
  # 2026-09-24: these were asserted as ">= 2 downhill LEFTS". With the corrected direction convention the
  # three binding clusters after 19:10 PT are 1 left + 2 right, so only their presence is asserted now.
  evening = [w for w in binding if w["t"] > 1783822200]
  assert len(evening) >= 2, "the 19:17 washouts are not in the registry"


def test_new_pipeline_caps_at_least_3mph_below_every_recorded_entry(tmp_path, monkeypatch):
  veh = _veh(tmp_path, monkeypatch)
  with open(FIXTURE) as f:
    washouts = json.load(f)["washouts"]
  checked = 0
  for w in washouts:
    if not w["binding"]:
      continue                                   # no binding cap recorded -> nothing to regress against
    pen = veh.curve_speed_penalty_ms(w["cap_ms"], pitch_rad=ASSUMED_GRADE_PITCH,
                                     is_left=(w["dir"] == "left"))
    new_cap = w["cap_ms"] - pen
    assert new_cap <= w["v_entry_ms"] - 3.0 * MPH, \
      f"{w['id']}: new cap {new_cap / MPH:.1f} mph not 3 mph below entry {w['v_entry_ms'] / MPH:.1f} mph"
    checked += 1
  assert checked >= 20


def test_icbm_sourced_caps_survive_the_map_rating_floor(tmp_path, monkeypatch):
  """icbmslow2pnw (Fable F2): the regression above applies `curve_speed_penalty_ms` to `cap_ms`, which
  is the VTSC pipeline. For clusters where `cap_ms` came from ICBM instead (tools/washouts.py:91-93
  falls back to the lowest ICBM target when no VTSC cap was recorded — the `shadow` clusters, i.e.
  stock-ACC drives), the applicable pipeline now also contains the map-rating floor, which that test
  does not model.

  Bounded here without needing the mapd rating, which the fixture does not carry: the floor can give
  back at most the BASE hump, and the hump is hard-capped at `penalty_cap_mph`. So `cap + 15 mph` is
  an upper bound on anything the floored pipeline can command at that site, whatever the candidate's
  rating was. Assert that bound still sits 3 mph below the speed the truck actually carried in.

  The three sites this covers are 2026-07-11 19:04:43 / 19:05:30 / 19:06:52 PT, entries 86-88 mph
  against caps of 51-58 mph: the truck was ~30 mph over ICBM's target, so the target was never the
  binding constraint there (the executor's 1 mph-per-tap walk-down was). They are deliberately NOT
  exempted on that argument — the bound is asserted."""
  veh = _veh(tmp_path, monkeypatch)
  with open(FIXTURE) as f:
    washouts = json.load(f)["washouts"]
  checked = 0
  for w in washouts:
    if not w["binding"] or not w.get("shadow"):
      continue
    upper = w["cap_ms"] + veh._curve_cfg["penalty_cap_mph"] * MPH
    assert upper <= w["v_entry_ms"] - 3.0 * MPH, \
      f"{w['id']}: floored bound {upper / MPH:.1f} mph not 3 below entry {w['v_entry_ms'] / MPH:.1f}"
    checked += 1
  assert checked >= 3, f"only {checked} ICBM-sourced binding washouts found -- the fixture is short"


def test_registry_never_used_for_control():
  """Guard: no control module may import/read the washout fixture (validation-only, driver rule)."""
  import glob
  root = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
  offenders = []
  for path in glob.glob(os.path.join(root, "**", "*.py"), recursive=True):
    if os.sep + "tests" + os.sep in path or path.endswith("washouts.py"):
      continue
    with open(path, encoding="utf-8", errors="ignore") as f:
      if "washouts_2026_07_11" in f.read():
        offenders.append(path)
  assert not offenders, f"washout fixture referenced by control code: {offenders}"
